// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperaX.Infrastructure.Persistence;

#nullable disable

namespace PaperaX.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617085002_RemoveMockCustomers")]
    partial class RemoveMockCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperaX.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstDelivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TotalString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5874),
                            CustomerName = "",
                            DateString = "May 14, 2026",
                            DeliveryMethod = "",
                            Destination = "Main Corporate Hub, Hassan Industrial Area, KA",
                            EstDelivery = "May 19, 2026",
                            ItemSummary = "JK Excel Bond A4 +1 more",
                            ItemsJson = "[{\"name\":\"JK Excel Bond A4 Office Paper\",\"qty\":\"20 Boxes\",\"price\":\"?44,000\"},{\"name\":\"Double Coated Art Sheet (250GSM)\",\"qty\":\"2 Packs\",\"price\":\"?10,000\"}]",
                            Payment = "",
                            Status = "shipped",
                            StringId = "#PX-ORDER-4921",
                            TotalAmount = 0m,
                            TotalString = "?54,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5881),
                            CustomerName = "",
                            DateString = "Apr 28, 2026",
                            DeliveryMethod = "",
                            Destination = "Logistics Center, Whitefield, BLR",
                            EstDelivery = "May 02, 2026",
                            ItemSummary = "Premium Specialty Kraft Rolls",
                            ItemsJson = "[{\"name\":\"Premium Specialty Kraft Rolls\",\"qty\":\"4 Rolls\",\"price\":\"?32,500\"}]",
                            Payment = "",
                            Status = "delivered",
                            StringId = "#PX-ORDER-4811",
                            TotalAmount = 0m,
                            TotalString = "?32,500",
                            UserId = 0
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5884),
                            CustomerName = "Aarav S.",
                            DateString = "24 Apr, 10:30 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "UPI",
                            Status = "Processing",
                            StringId = "#PX-101",
                            TotalAmount = 0m,
                            TotalString = "?4,500",
                            UserId = 0
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5887),
                            CustomerName = "B2B: Paper Solutions",
                            DateString = "24 Apr, 09:15 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "NEFT",
                            Status = "Shipped",
                            StringId = "#PX-102",
                            TotalAmount = 0m,
                            TotalString = "?85,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5889),
                            CustomerName = "Meera K.",
                            DateString = "23 Apr, 06:45 PM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "COD",
                            Status = "Delivered",
                            StringId = "#PX-103",
                            TotalAmount = 0m,
                            TotalString = "?1,200",
                            UserId = 0
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5892),
                            CustomerName = "Global Export",
                            DateString = "23 Apr, 04:20 PM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "Wire",
                            Status = "Pending",
                            StringId = "#PX-104",
                            TotalAmount = 0m,
                            TotalString = "?4,20,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(2026, 6, 17, 8, 50, 0, 864, DateTimeKind.Utc).AddTicks(5894),
                            CustomerName = "Rohan J.",
                            DateString = "22 Apr, 11:00 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "Card",
                            Status = "Delivered",
                            StringId = "#PX-105",
                            TotalAmount = 0m,
                            TotalString = "?8,500",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GSM")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Product", b =>
                {
                    b.HasOne("PaperaX.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
