// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperaX.Infrastructure.Persistence;

#nullable disable

namespace PaperaX.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615073059_AddCategoryEntity")]
    partial class AddCategoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperaX.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3984),
                            Description = "Standard A4 size copier papers",
                            IsActive = true,
                            Name = "A4 Paper",
                            Slug = "a4-paper"
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4095),
                            Description = "Large A3 size printing papers",
                            IsActive = true,
                            Name = "A3 Paper",
                            Slug = "a3-paper"
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4097),
                            Description = "Specialty printing and photo papers",
                            IsActive = true,
                            Name = "Specialty",
                            Slug = "specialty"
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4099),
                            Description = "Kraft and packaging solutions",
                            IsActive = true,
                            Name = "Packaging",
                            Slug = "packaging"
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4100),
                            Description = "Notebooks, diaries, and refills",
                            IsActive = true,
                            Name = "Notebooks",
                            Slug = "notebooks"
                        });
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstDelivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TotalString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4206),
                            CustomerName = "",
                            DateString = "May 14, 2026",
                            DeliveryMethod = "",
                            Destination = "Main Corporate Hub, Hassan Industrial Area, KA",
                            EstDelivery = "May 19, 2026",
                            ItemSummary = "JK Excel Bond A4 +1 more",
                            ItemsJson = "[{\"name\":\"JK Excel Bond A4 Office Paper\",\"qty\":\"20 Boxes\",\"price\":\"?44,000\"},{\"name\":\"Double Coated Art Sheet (250GSM)\",\"qty\":\"2 Packs\",\"price\":\"?10,000\"}]",
                            Payment = "",
                            Status = "shipped",
                            StringId = "#PX-ORDER-4921",
                            TotalAmount = 0m,
                            TotalString = "?54,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4210),
                            CustomerName = "",
                            DateString = "Apr 28, 2026",
                            DeliveryMethod = "",
                            Destination = "Logistics Center, Whitefield, BLR",
                            EstDelivery = "May 02, 2026",
                            ItemSummary = "Premium Specialty Kraft Rolls",
                            ItemsJson = "[{\"name\":\"Premium Specialty Kraft Rolls\",\"qty\":\"4 Rolls\",\"price\":\"?32,500\"}]",
                            Payment = "",
                            Status = "delivered",
                            StringId = "#PX-ORDER-4811",
                            TotalAmount = 0m,
                            TotalString = "?32,500",
                            UserId = 0
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4214),
                            CustomerName = "Aarav S.",
                            DateString = "24 Apr, 10:30 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "UPI",
                            Status = "Processing",
                            StringId = "#PX-101",
                            TotalAmount = 0m,
                            TotalString = "?4,500",
                            UserId = 0
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4217),
                            CustomerName = "B2B: Paper Solutions",
                            DateString = "24 Apr, 09:15 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "NEFT",
                            Status = "Shipped",
                            StringId = "#PX-102",
                            TotalAmount = 0m,
                            TotalString = "?85,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4219),
                            CustomerName = "Meera K.",
                            DateString = "23 Apr, 06:45 PM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "COD",
                            Status = "Delivered",
                            StringId = "#PX-103",
                            TotalAmount = 0m,
                            TotalString = "?1,200",
                            UserId = 0
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4221),
                            CustomerName = "Global Export",
                            DateString = "23 Apr, 04:20 PM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "Wire",
                            Status = "Pending",
                            StringId = "#PX-104",
                            TotalAmount = 0m,
                            TotalString = "?4,20,000",
                            UserId = 0
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(4223),
                            CustomerName = "Rohan J.",
                            DateString = "22 Apr, 11:00 AM",
                            DeliveryMethod = "",
                            Destination = "",
                            EstDelivery = "",
                            ItemSummary = "",
                            ItemsJson = "",
                            Payment = "Card",
                            Status = "Delivered",
                            StringId = "#PX-105",
                            TotalAmount = 0m,
                            TotalString = "?8,500",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GSM")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -1,
                            Description = "",
                            GSM = 75,
                            ImageUrl = "",
                            Name = "Premium A4 Copier Paper",
                            Price = 250m,
                            Status = "In Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -2,
                            CategoryId = -1,
                            Description = "",
                            GSM = 80,
                            ImageUrl = "",
                            Name = "Color Print Paper (Assorted)",
                            Price = 300m,
                            Status = "Low Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -3,
                            CategoryId = -2,
                            Description = "",
                            GSM = 80,
                            ImageUrl = "",
                            Name = "A3 Executive Paper",
                            Price = 450m,
                            Status = "In Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -4,
                            CategoryId = -3,
                            Description = "",
                            GSM = 180,
                            ImageUrl = "",
                            Name = "Photo Glossy Paper",
                            Price = 600m,
                            Status = "In Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -5,
                            CategoryId = -4,
                            Description = "",
                            GSM = 100,
                            ImageUrl = "",
                            Name = "Recycled Kraft Paper",
                            Price = 150m,
                            Status = "Low Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -6,
                            CategoryId = -3,
                            Description = "",
                            GSM = 250,
                            ImageUrl = "",
                            Name = "Cardstock Heavy",
                            Price = 800m,
                            Status = "In Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -7,
                            CategoryId = -5,
                            Description = "",
                            GSM = 70,
                            ImageUrl = "",
                            Name = "A5 Notebook Refills",
                            Price = 120m,
                            Status = "In Stock",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = -8,
                            CategoryId = -3,
                            Description = "",
                            GSM = 55,
                            ImageUrl = "",
                            Name = "Thermal Receipt Rolls",
                            Price = 50m,
                            Status = "Low Stock",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Company = "N/A",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3740),
                            Email = "aarav.sharma@gmail.com",
                            FullName = "Aarav Sharma",
                            IsEmailVerified = true,
                            OrdersCount = 12,
                            PasswordHash = "",
                            Phone = "+91 98765 43210",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 45000m,
                            Type = "Retail"
                        },
                        new
                        {
                            Id = -2,
                            Company = "Paper Solutions Ltd",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3749),
                            Email = "v.mehta@papersolutions.com",
                            FullName = "Vikram Mehta",
                            IsEmailVerified = true,
                            OrdersCount = 24,
                            PasswordHash = "",
                            Phone = "+91 22 4567 8901",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 850000m,
                            Type = "B2B"
                        },
                        new
                        {
                            Id = -3,
                            Company = "N/A",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3754),
                            Email = "meera.k@yahoo.com",
                            FullName = "Meera Kapoor",
                            IsEmailVerified = true,
                            OrdersCount = 5,
                            PasswordHash = "",
                            Phone = "+91 87654 32109",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 12400m,
                            Type = "Retail"
                        },
                        new
                        {
                            Id = -4,
                            Company = "Global Export Inc.",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3758),
                            Email = "j.doe@globalexport.com",
                            FullName = "John Doe",
                            IsEmailVerified = true,
                            OrdersCount = 8,
                            PasswordHash = "",
                            Phone = "+1 415 555 2671",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 1420000m,
                            Type = "B2B"
                        },
                        new
                        {
                            Id = -5,
                            Company = "N/A",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3761),
                            Email = "rohan.j@rediffmail.com",
                            FullName = "Rohan Joshi",
                            IsEmailVerified = true,
                            OrdersCount = 9,
                            PasswordHash = "",
                            Phone = "+91 76543 21098",
                            Role = "Customer",
                            Status = "Inactive",
                            TotalSpent = 76500m,
                            Type = "Retail"
                        },
                        new
                        {
                            Id = -6,
                            Company = "Creative Prints",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3768),
                            Email = "ananya@creativeprints.in",
                            FullName = "Ananya Sen",
                            IsEmailVerified = true,
                            OrdersCount = 18,
                            PasswordHash = "",
                            Phone = "+91 33 2445 6677",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 340000m,
                            Type = "B2B"
                        },
                        new
                        {
                            Id = -7,
                            Company = "Birla Publications",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3771),
                            Email = "aditya@birlapub.com",
                            FullName = "Aditya Birla",
                            IsEmailVerified = true,
                            OrdersCount = 32,
                            PasswordHash = "",
                            Phone = "+91 22 8877 6655",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 1890000m,
                            Type = "B2B"
                        },
                        new
                        {
                            Id = -8,
                            Company = "N/A",
                            CreatedAt = new DateTime(2026, 6, 15, 7, 30, 57, 741, DateTimeKind.Utc).AddTicks(3775),
                            Email = "pooja.h@outlook.com",
                            FullName = "Pooja Hegde",
                            IsEmailVerified = true,
                            OrdersCount = 3,
                            PasswordHash = "",
                            Phone = "+91 99887 76655",
                            Role = "Customer",
                            Status = "Active",
                            TotalSpent = 8900m,
                            Type = "Retail"
                        });
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Product", b =>
                {
                    b.HasOne("PaperaX.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PaperaX.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
